version: '2'
services:
  php:
    build: .
    depends_on:
      - db
  db:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=devops_app #creará una base de datos con ese nombre
      - MYSQL_ROOT_PASSWORD=root #clave de administrador del servidor MySQL
